[package]
name = "gdax_refine"
version = "0.1.0"
authors = ["Paul G Webster <paul.g.webster@googlemail.com>"]
edition = "2018"

[dependencies]
redis = "0.20.0"
dirs = "3.0.1"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
